### PR TITLE
More tests

### PR DESCRIPTION
**Pull request by taty2010**
# Description
Created more tests for the Dashboard 
## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Change Status

- [X] Complete, tested, ready to review and merge
- [ ] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

## How Has This Been Tested?

- [X] Cypress
- [ ] Test B

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] There are no merge conflicts

### CODE REVIEW

**Review by ccsmith13 — APPROVED** [review]

**Comment by taty2010** [comment]
Tests are not passing when creating PR but are passing locally

**Comment by dave-vazquez** [comment]
Reopening to see if applied changes make the tests run on PR creation.

**Review by dave-vazquez — APPROVED** [review]

**Comment by dave-vazquez** [comment]
hold off deleting this branch

**Comment by dave-vazquez** [comment]
okay, this is no biggie - they updated the CC secrets which is why it's not publishing, we can fix this on the next RC, let's leave the branch open for now

**Pull request merged**
