### PR TITLE
Bmi calc/validation

### PR DESCRIPTION
**Pull request by taty2010**
# Description
Added Validation to BMI Calculator for standard and metric 
Removed calc function so BMI total would update automatically
Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)

## Change Status

- [X] Complete, tested, ready to review and merge
- [ ] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

## How Has This Been Tested?

- [X] Tested out validation and calculation total on local server 
- [ ] Test B

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] There are no merge conflicts

### CODE REVIEW

**Review by CodyBrewer — COMMENTED** [review]
Everything is looking good.  It looks like the Labels and Inputs aren't associated together which will cause some accessibility issues. The labels are missing htmlFor attribute and inputs are missing the id attribute to associate the label with.

**Comment by taty2010** [comment]
[BMI-Calc / Validation](https://trello.com/c/SKYUgenF/75-bmi-calc-validation)

**Comment by taty2010** [comment]
> Everything is looking good. It looks like the Labels and Inputs aren't associated together which will cause some accessibility issues. The labels are missing htmlFor attribute and inputs are missing the id attribute to associate the label with.

Thanks for catching that, I'll go ahead and look into it and make those changes.

**Review by ccsmith13 — APPROVED** [review]
good work, and thanks for updating the accessibility too

**Review by alesslongaretti — APPROVED** [review]

**Pull request merged**
