### PR TITLE
initial testing for signin page

### PR DESCRIPTION
**Pull request by ccsmith13**
# Description
set up initial testing for the sign in page that mirror the sign up page 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] There are no merge conflicts

### CODE REVIEW

**Comment by ccsmith13** [comment]
[Sign In - Testing](https://trello.com/c/MZoX2aj2/78-sign-in-testing)

**Review by alesslongaretti — APPROVED** [review]
Great Job!

**Review by taty2010 — CHANGES_REQUESTED** [review]
Thanks for adding the testing for sign in

**Review by taty2010 — APPROVED** [review]
Sorry meant to approve : )

**Pull request merged**
